### ISSUE TITLE
Icon request: Disk Inventory X

### ISSUE THREAD

**Issue by dbkaplun** [tinalatif/flat.icns#162]

**Comment by mcallinder** [comment]
+1

**Comment by wjramos** [comment]
I'm going to say this one is not really up to par
![diskinventoryx](https://cloud.githubusercontent.com/assets/5625810/8018346/a080566a-0bcc-11e5-8d70-6587144f63c7.png)

**Comment by wjramos** [comment]
![diskinventoryx](https://cloud.githubusercontent.com/assets/5625810/8018412/5b430572-0bcf-11e5-95e1-fd509317b179.png)

**Comment by dbkaplun** [comment]
:heart_eyes:

**Comment by mknrls** [comment]
@wjramos nice work man, that second one is awesome. Really like it :+1:

**Comment by wjramos** [comment]
Cool, I'll go ahead and issue a pull request then

**Comment by tinalatif** [comment]
I think it would fit the icon set better if instead of having a purple container with a white inner-icon, the inner-icon just filled the entire square (with inverted colors so the body was purple with white lines). I guess it would be a combination of version 1 and version 2 - the way #1 fills the icon but with the minimalism of #2

**Comment by wjramos** [comment]
![disk-inventory-x](https://cloud.githubusercontent.com/assets/5625810/8101060/449423c2-0fc8-11e5-9648-90b5b36bf021.png)

**Comment by tinalatif** [comment]
Cool! Looks great

**Comment by dbkaplun** [comment]
@wjramos can we get a PR? :palm_tree:

**Comment by wjramos** [comment]
PR issued #201 - please note I made the lines a little wider and less intense, plus chose what I feel was a better base purple

**Comment by tinalatif** [comment]
Merged at 0f84c1ba53d3837d0b9b0365ef774e82880999cf
