### ISSUE TITLE
Icon Request: VMWare Fusion

### ISSUE THREAD

**Issue by mcallinder** [tinalatif/flat.icns#177]
http://www.vmware.com/products/fusion

![VMWare Fusion](http://www.macupdate.com/images/icons256/23593.png)

**Comment by ejgisbertm** [comment]
Take a look at this one, hope it fits well with the theme.

![fusion](https://cloud.githubusercontent.com/assets/13053885/8440841/ac689f98-1f3e-11e5-810c-63c5d7d4d516.png)

**Comment by tinalatif** [comment]
Not bad. I'd round the corners to fit with the original icon and theme

**Comment by ejgisbertm** [comment]
Will do @tinalatif. Also, I'll try to expand both squares so it fits the icon area edge to edge. By the way, please check #157, I made an attempt there too.
As I explain in that issue, I'm not good at vectors, only (barely) competent with rasters. If this is not a problem, and the icons are good enough, I can fork and then send a pull request; your call.

**Comment by wjramos** [comment]
I'd be happy to recreate your design as a vector

**Comment by ejgisbertm** [comment]
That would be great @wjramos 

Really, I struggle a lot in the art department, after all, I'm just a sysadmin. Anyway, I made a second version of the icon with @tinalatif comments taken into account. Here it is for all of you to check:

![vmware](https://cloud.githubusercontent.com/assets/13053885/8504107/c8464d5c-2194-11e5-8e16-b4dcd4a747f4.png)

Please criticise it as much as you want, it's the better way to crop out the rough edges.

Also, check the TeamViewer icon I made for issue #157 to see if it blends well with the set. You are also welcome to vectorise it if you want.

Best regards to all.

**Comment by tinalatif** [comment]
Both are great icons, but I would like to keep the format consistent. Also
happy to recreate them as vectors next week if @wjramos hasn't already!

**Comment by wjramos** [comment]
So,  in the AI template there is an inner and outer bounding box, each with a border radius, I think in order for it to match the theme it needs to take advantage of the sizing (either full width or encapsulated) and border radius in the template

**Comment by ejgisbertm** [comment]
@wjramos, I originally made the icon in PowerPoint (Yeah, I know... ). If you'd like to have the file in order to manipulate the elements, just download it from my Dropbox:

https://www.dropbox.com/s/dhtorqp9pk4gqkr/vmware.pptx?dl=0

I'm not sure if this would help or hinder you in order to create the .AI file format. Earlier I used Image2Icon in order to convert the .PNG file to .ICNS for testing purposes and they look fine both in shape and hue.

**Comment by wjramos** [comment]
![vmware](https://cloud.githubusercontent.com/assets/5625810/8541144/d24533be-2440-11e5-8cc3-80a82ba1a2d8.png)

**Comment by ejgisbertm** [comment]
Nice work @wjramos, you make it look very easy :-)

Let us wait for the owner's input on this, but if you ask me, both icons are terrific.

**Comment by wjramos** [comment]
In retrospect, the white segment did not resemble a set of arrows too much, and the heads of the arrows were a tad too big causing the colored segment line thicknesses to not be consistent
![vmware](https://cloud.githubusercontent.com/assets/5625810/8577963/a21d27fc-2560-11e5-9cf9-2a63d82d4c02.png)

**Comment by ejgisbertm** [comment]
Hmm, I see what you mean with the arrows. To be honest, my eyes dismissed the roundness of the tip of the arrow. Yes, the above one does look better.

About the background, I took a glance to all the icons in the set and didn't notice any with a transparent background. I think that in order to keep the set consistent all of them have a background. Maybe if you try in another color? A light grey? You could even reduce the logo just one or two pixels (is that even possible with vectors?) so the light grey (or whatever color) background frames the logo entirely.

Something like this (note, scale is off, it's just a quick mock up):

![untitled](https://cloud.githubusercontent.com/assets/13053885/8587027/47b41ebe-25c0-11e5-845a-6a367fd247a3.png)

**Comment by wjramos** [comment]
I think the only way to have the solid frame with the icon would be using the inner bounding box
![vmware](https://cloud.githubusercontent.com/assets/5625810/8599821/6a8a59ec-2617-11e5-8813-e5e51db1f931.png)

**Comment by ejgisbertm** [comment]
Well, to be honest, I kind of like it that way @wjramos. It looks way better.

**Comment by wjramos** [comment]
Pull request issued #202

**Comment by tinalatif** [comment]
Merged at a24bf03d8a87dd10174eca0f1f6b2f8e965146c5
